<a href="https://colab.research.google.com/github/superbijk/cityweatherdata/blob/master/assignment1_weather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
#import numpy library
import numpy as np
import pandas as pd

#import np dataset from github
url = 'https://raw.githubusercontent.com/superbijk/cityweatherdata/master/cityweatherdata.csv'
df = pd.read_csv(url)

#preview data frame
df.head(3)

m1  m2  m3  m4  m5  m6  m7  m8  m9  m10  m11  m12
0  -2  -2   2   8  14  19  21  20  16   10    4    1
1  20  20  22  23  26  27  28  28  27   26   23   20
2  -1   1   6  13  18  23  26  25  21   15    7    1

In [84]:
#convert to numpy
x = df.to_numpy()
print(x)

[[-2 -2  2  8 14 19 21 20 16 10  4  1]
 [20 20 22 23 26 27 28 28 27 26 23 20]
 [-1  1  6 13 18 23 26 25 21 15  7  1]
 [11 13 16 20 23 27 27 27 26 21 16 12]
 [-8 -5  0  7 14 19 22 20 16 10  2 -5]
 [10 12 16 20 23 27 28 28 26 21 16 12]
 [12 14 16 21 26 31 33 32 30 23 16 12]
 [ 5  6  7 10 13 16 18 18 16 12  8  6]
 [10 12 12 13 14 15 15 16 17 16 14 11]
 [13 14 15 16 17 19 21 22 21 19 16 14]]


In [108]:
#problem 1: find an average temp for each city
avgcities = np.round(x.sum(axis=1) / 12,1)

for i, avgcity in enumerate(avgcities):
  print('Number {} city\'s average temperature is {}'.format(i+1, avgcity))

Number 1 city's average temperature is 9.2
Number 2 city's average temperature is 24.2
Number 3 city's average temperature is 12.9
Number 4 city's average temperature is 19.9
Number 5 city's average temperature is 7.7
Number 6 city's average temperature is 19.9
Number 7 city's average temperature is 22.2
Number 8 city's average temperature is 11.2
Number 9 city's average temperature is 13.8
Number 10 city's average temperature is 17.2


In [130]:
#problem 2: find an average, minimum, maximum temp for each season
seasons_dict = {'Winter': [0,1,2], 'Spring': [3,4,5], 'Summer': [6,7,8], 'Authumn' : [9,10,11]}

for season, months in seasons_dict.items():
  season_avg = np.round(x[:,months].sum() / (len(months)*x.shape[0]), 1)
  print('{} average temperature is {}'.format(season, season_avg))
  print('{} minimum temperature is {}'.format(season, x[:,months].min()))
  print('{} maximum temperature is {}'.format(season, x[:,months].max()))
  print('\n')



Winter average temperature is 8.9
Winter minimum temperature is -8
Winter maximum temperature is 22


Spring average temperature is 18.7
Spring minimum temperature is 7
Spring maximum temperature is 31


Summer average temperature is 23.0
Summer minimum temperature is 15
Summer maximum temperature is 33


Authumn average temperature is 12.6
Authumn minimum temperature is -5
Authumn maximum temperature is 26


